export const motivationalQuotes = [
  "Small steps today build the career you dream about.",
  "Your future is built in the sessions you show up for.",
  "Progress may be slow, but standing still won't take you there.",
  "Study today for the opportunities you want tomorrow.",
  "Consistency turns ordinary effort into extraordinary results.",
  "Every page you study is an investment in your future.",
  "Your dream career deserves your disciplined effort.",
  "You don't need to be perfect. You need to keep going.",
  "One focused session can change the direction of your day.",
  "The struggle is part of becoming who you want to be.",
  "Keep learning. Your future opportunities are being prepared for.",
  "Discipline carries you forward when motivation fades.",
  "Today's effort becomes tomorrow's confidence.",
  "Your goals are bigger than today's temporary difficulty.",
  "Every concept understood is another step toward your goal.",
  "You are building skills that your future self will need.",
  "Progress is still progress, even when nobody sees it.",
  "The career you want is built one skill at a time.",
  "Keep showing up. Your effort is adding up.",
  "A difficult chapter can still lead to a beautiful future.",
  "Your current struggle does not define your final destination.",
  "Learn now. Grow now. Your opportunities will follow.",
  "The hours you invest today can create years of opportunity.",
  "Don't underestimate what consistent effort can achieve.",
  "Your dream deserves more than occasional effort.",
  "Every study session makes you a little more capable.",
  "You are closer than you were yesterday.",
  "Keep going, especially on the days it feels slow.",
  "Your future career starts with what you choose to learn today.",
  "One more session. One more concept. One step closer.",
  "Hard work feels different when you know what you're working toward.",
  "You don't have to finish everything today. Just move forward.",
  "Build knowledge before you need it.",
  "The person you want to become is built through today's habits.",
  "Your effort today is creating options for tomorrow.",
  "Stay patient with the process and committed to the goal.",
  "Learning compounds just like every good investment.",
  "Your setbacks are moments, not your final story.",
  "Keep investing in yourself. The returns take time.",
  "A strong career is built on skills earned quietly over time.",
  "You can be tired and still take one small step forward.",
  "Your consistency matters more than your occasional perfect day.",
  "Every difficult topic you conquer builds confidence.",
  "The goal is not to know everything. The goal is to keep learning.",
  "Your dream job begins with becoming ready for it.",
  "Study for the life you want, not just the exam in front of you.",
  "Your future opportunities are worth today's discipline.",
  "Keep your eyes on the destination and your focus on today's task.",
  "One productive hour is better than hours spent worrying.",
  "You are not behind. You are building at your own pace.",
  "Your journey may be difficult, but your direction still matters.",
  "Believe in the version of yourself you are working toward.",
  "Confidence grows when preparation meets persistence.",
  "The days that test you can also strengthen you.",
  "Don't let a difficult session convince you to quit the journey.",
  "Your effort counts even when the results take time to appear.",
  "Every revision makes your foundation stronger.",
  "Keep learning until the things that once felt difficult become familiar.",
  "The dream is the destination. Consistency is the road.",
  "Your career can change through skills you start building today.",
  "A better future is created through better habits.",
  "Keep preparing for opportunities before they arrive.",
  "Your study desk can be the starting point of a bigger life.",
  "You are building more than knowledge. You are building capability.",
  "Small improvements repeated daily become remarkable progress.",
  "The work you do quietly today can speak loudly tomorrow.",
  "Don't measure your journey by someone else's timeline.",
  "Your pace does not matter as much as your persistence.",
  "Keep going. The version of you with the dream career needs you to.",
  "Every focused session is proof that you haven't given up.",
  "The road may be long, but every step has value.",
  "Learn from the struggle instead of letting it stop you.",
  "Your future deserves the effort your present self can give.",
  "You don't need more time. Start with the time you have.",
  "Progress begins when you choose to show up again.",
  "The skills you build today can open doors tomorrow.",
  "Stay consistent when the excitement disappears.",
  "Your goals require patience, preparation, and persistence.",
  "One chapter completed is better than one chapter postponed.",
  "Keep building. Your breakthrough may come from skills you are learning now.",
  "Your dream career is not built overnight. It is built daily.",
  "Preparation turns opportunities into possibilities.",
  "The more you learn, the more opportunities you can create.",
  "Your difficult days are still part of your success story.",
  "Keep your ambition high and your daily actions simple.",
  "You are allowed to struggle. Just don't stop progressing.",
  "Every mistake can become part of your learning curve.",
  "Your future self is counting on today's discipline.",
  "Make today's session count, even if it is a small one.",
  "The goal may be far away, but today's step is always within reach.",
  "Keep believing while you keep building.",
  "Your circumstances can change when your skills and persistence grow.",
  "Study with purpose. Work with patience. Grow with consistency.",
  "The career you imagine starts with the knowledge you build now.",
  "You are becoming more prepared with every session.",
  "Don't wait to feel motivated. Start, and let momentum follow.",
  "Your effort is not wasted just because progress is invisible.",
  "Keep learning through the uncertainty. Your path will become clearer.",
  "Dream big, but build patiently.",
  "Every day you continue is another day you refuse to give up.",
  "Your future can be different because of what you do today.",
];

export function getRandomQuote() {
  const randomIndex = Math.floor(Math.random() * motivationalQuotes.length);
  return motivationalQuotes[randomIndex];
}
